services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET_KEY
        generateValue: true
